### ISSUE TITLE
ARM64

### ISSUE THREAD

**Issue by gadgetsnewsnet** [zerolabnet/tor-bridges-proxy#1]
При установке пишет:

> failed to deploy a stack: tor-bridges-proxy Pulling no matching manifest for linux/arm64/v8 in the manifest list entries 

Можно ли добавить поддержку arm64?

**Comment by zerolabnet** [comment]
obfs4proxy нет под arm64 в Alpine Linux. На arm64 можно поставить пакет под arm v7 так:

docker run -d \
--platform linux/arm/v7 \
--name tor-bridges-proxy \
--restart=unless-stopped \
-p 9150:9150/tcp \
-p 9151:9151/tcp \
-p 53:9053/udp \
zerolabnet/tor-bridges-proxy:latest
